version: '3'

services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile 
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${SU_POSTGRES_PASS}
      PG_DATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - ${BMON_POSTGRES_PORT}:${BMON_POSTGRES_PORT}
    networks:
      - main
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${BMON_POSTGRES_DB} -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  main:

volumes:
  db: