replicaCount: 1

specs:
  server:
    repository: bmon-odds/server
    name: bmon-odds-server
    pullPolicy: IfNotPresent
    tag: latest
    securityContext: {}
    containerPort: 80
    livenessProbe:
      initialDelaySeconds: 30
      httpGet:
        path: /api/sports
        port: 8080
    readinessProbe:
      initialDelaySeconds: 20
      httpGet:
        path: /api/sports
        port: 8080
    resources: {}
    volumes: []
    volumeMounts: []
    nodeSelector: {}
    tolerations: []
    affinity: {}
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  name: backend-service
  type: ClusterIP
  port: 43

# TODO: resolve duplicate nginx instances
# TODO: rewrite the ingress.yaml
ingress:
  enabled: true
  className: nginx
  annotations: 
    #nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    #nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    #nginx.ingress.kubernetes.io/hsts: 'true'
    #nginx.ingress.kubernetes.io/hsts-include-subdomains: 'true'
    #nginx.ingress.kubernetes.io/hsts-max-age: '31536000'

  hosts:
    - host: bmon-odds.local
      paths:
        - path: "/"
          pathType: "Prefix"
          backend:
            service: "backend-service"
            port: 8080
  tls:
    - hosts:
      - bmon-odds.local
      secretName: ingress-tls-certs

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

#env
postgresql:
  enabled: true
  primary:
    name: NAME_CHANGETHIS
    initdb:
      scriptsConfigMap: "configmap-postgresql-init"

# TODO: figure out how to split the postgressql-secret into 2, one for global without the su password and one internally with.
global:
  postgresql:
    auth:
      username: USERNAME_CHANGETHIS
      database: DATABASE_CHANGETHIS
      existingSecret: postgresql-secrets
      url: URL_CHANGETHIS
    service:
      ports:
        postgresql: 5432

bmonodds:
  server:
    spring:
      profilesActive: PROFILES_ACTIVE_CHANGETHIS
      debug: DEBUG_CHANGETHIS
    schema:
      app: APP_SCHEMA_CHANGETHIS
      flyway: FLYWAY_SCHEMA_CHANGETHIS
