# set -o allexport && source .env && set +o allexport

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring: 
  debug: ${SPRING_DEBUG}
  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: validate
  flyway:
    createSchemas: true
    defaultSchema: ${FLYWAY_SCHEMA}
    initSql: CREATE IF NOT EXISTS ${FLYWAY_SCHEMA};
  