# set -o allexport && source .env && set +o allexport

logging:
  level:
    org:
      hibernate:
        # log statements(SQL) and parameter values(type.)
        # SQL: DEBUG
        # type.descriptor.sql: TRACE
      # log requests
      springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring: 
  debug: ${SPRING_DEBUG}
  jpa:
    show-sql: true
    hibernate:
      # TODO: fix validation errors
      # ddl-auto: validate
  flyway:
    createSchemas: true
    defaultSchema: ${FLYWAY_SCHEMA}
    initSql: CREATE IF NOT EXISTS ${FLYWAY_SCHEMA};
  