apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.service.name }}
  labels:
    {{- include "bmonodds.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ingress.service.type }}
  ports:
    - port: {{ .Values.ingress.service.port }}
      targetPort: 443
      protocol: TCP
      name: http
  selector:
    {{- include "bmonodds.selectorLabels" . | nindent 4 }}
