CREATE TYPE "${POSTGRES_SCHEMA}"."bet_status" AS ENUM
('WIN', 'LOSS', 'PENDING', 'VOID');

CREATE TABLE "${POSTGRES_SCHEMA}"."default_columns"
(
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "${POSTGRES_SCHEMA}"."markets"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,	
	name TEXT
);

CREATE TABLE "${POSTGRES_SCHEMA}"."sports"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,	
	name TEXT
);

CREATE TABLE "${POSTGRES_SCHEMA}"."players"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,	
	firstname TEXT NOT NULL,
	lastname TEXT NOT NULL,
	slug TEXT NOT NULL,
	country_code TEXT NOT NULL
);

CREATE TABLE "${POSTGRES_SCHEMA}"."leagues"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,	
	name TEXT
);

CREATE TABLE "${POSTGRES_SCHEMA}"."matches"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,
	live BOOLEAN DEFAULT TRUE,
	leagues_id INTEGER REFERENCES "${POSTGRES_SCHEMA}"."leagues" (id) ON DELETE SET NULL,
	sports_id INTEGER REFERENCES  "${POSTGRES_SCHEMA}"."sports" (id) ON DELETE SET NULL,
	name TEXT
);

CREATE TABLE "${POSTGRES_SCHEMA}"."match_states"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,
	matches_id INTEGER REFERENCES "${POSTGRES_SCHEMA}"."matches" (id) ON DELETE CASCADE NOT NULL,
	point_score TEXT NOT NULL,
	serving_index numeric (1) NOT NULL,
	set_score text NOT NULL
);

CREATE TABLE "${POSTGRES_SCHEMA}"."market_states"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,
	markets_id INTEGER REFERENCES "${POSTGRES_SCHEMA}"."markets" (id) ON DELETE SET NULL,
	players_id INTEGER REFERENCES "${POSTGRES_SCHEMA}"."players" (id) ON DELETE SET NULL,
	match_states_id INTEGER REFERENCES "${POSTGRES_SCHEMA}"."match_states" (id) ON DELETE CASCADE NOT NULL,
	odd NUMERIC(5, 2) DEFAULT 1,
	suspended BOOLEAN NOT NULL DEFAULT FALSE,
	stake_limit NUMERIC (10,2) NOT NULL DEFAULT 100
);

CREATE TABLE "${POSTGRES_SCHEMA}"."users"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,
	balance NUMERIC(10, 2) NOT NULL DEFAULT 0,
	username text NOT NULL UNIQUE,
	password text NOT NULL
);

CREATE TABLE "${POSTGRES_SCHEMA}"."bets"
(
	LIKE "${POSTGRES_SCHEMA}"."default_columns",
	id BIGSERIAL PRIMARY KEY,
	stake NUMERIC(10,2) NOT NULL,
	status "${POSTGRES_SCHEMA}"."bet_status" NOT NULL DEFAULT 'PENDING',
	to_return NUMERIC(10,2) NOT NULL,
	market_states_id INTEGER REFERENCES "${POSTGRES_SCHEMA}"."market_states" (id) ON DELETE SET NULL,
	users_id INTEGER REFERENCES "${POSTGRES_SCHEMA}"."users" (id) ON DELETE CASCADE NOT NULL
);

